stages:          # List of stages for jobs, and their order of execution
  - build master

build-job main:
  stage: build master
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  tags :
    - linux
  only :
    - master