stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA


publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - cd backend
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST


deploy:
  image: alpine:latest
  stage: deploy 
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose build up --build"
  environment:
    name: production
    url: http://138.68.64.207
  only:
    - master 
