stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job main:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  tags :
    - linux
  only :
    - master

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
