stages:
  - deploy   


deploy:   
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p$PORT_RSA "git reset --hard HEAD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p$PORT_RSA "git pull origin master"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p$PORT_RSA "docker compose down"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p$PORT_RSA "docker compose -f docker-compose.prod.yaml up --build --detach"



  environment:
    name: production
    url: http://$SERVER_IP
  only: 
    - master  
