stages:          # List of stages for jobs, and their order of execution
  - build master

build-job main:
  stage: build master
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - rm -rf /home/ubuntu/*
    - cp -r * /home/ubuntu/
    - cp -r . /home/ubuntu/
    - rm -rf *
  tags :
    - linux
  only :
    - master