stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA


publish: 
  image: docker:latest
  stage: publish
  services:
    - docker:dind  
  script:
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker-compose build
    - docker-compose push

deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - deployment
  script:
    - apk update && apk add openssh-client
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login registry.gitlab.com -u $USERNAME -p $PASSWORD"    
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_IP "docker-compose pull"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_IP "docker-compose up -d"
  environment:
    name: production
    url: http://161.35.222.79
  only:
    - master
