stages:
  - build
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker-compose build

publish:
  stage: publish
  script:
    - docker-compose push

deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - deployment
  script:
    - apk update && apk add openssh-client
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose pull"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose up -d"
  environment:
    name: production
    url: http://161.35.222.79
  only:
    - master
