stages:
  - test
  - delivery


test-job:
  stage: test
  script:
    - docker-compose down
    - docker-compose build .
    - docker-compose up --build

delivery-job:
  stage: delivery
  only:
    - master
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u $DOCKER_REGISTRY_USER  registry.gitlab.com
    - docker tag linux $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE