stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA


publish:
  stage: publish
  image:
    name: docker/compose:latest
  script:
    - docker-compose -f docker-compose.yml build
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker-compose -f docker-compose.yml push

deploy:
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login registry.gitlab.com -u $USERNAME -p $PASSWORD"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose -f docker-compose.yml pull"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose -f docker-compose.yml up -d"

  environment:
    name: production
    url: http://161.35.222.79

  only:
    - master

services:
  - docker:19.03.12-dind

