stages:
  - test
  - delivery


test-job:
  stage: test
  script:
    - snap install docker
    - ls
    - docker-compose -f docker-compose.yaml down
    - docker-compose -f docker-compose.yaml build .
    - docker-compose -f docker-compose.yaml up --build

delivery-job:
  stage: delivery
  only:
    - master
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u $DOCKER_REGISTRY_USER  registry.gitlab.com
    - docker tag linux $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
