# Generated by Django 5.0.6 on 2024-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0004_alter_threedmodel_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='path',
            field=models.FileField(upload_to='3d_models/'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='path_env_image',
            field=models.FileField(null=True, upload_to='env_images/'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='path_skybox_image',
            field=models.FileField(null=True, upload_to='skybox_images/'),
        ),
    ]
