# Generated by Django 5.0.6 on 2024-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0005_alter_threedmodel_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
