"""Change fields

Revision ID: 9bd37009e070
Revises: b81dffe5cd49
Create Date: 2024-03-27 22:41:27.085550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9bd37009e070'
down_revision: Union[str, None] = 'b81dffe5cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('path_env_image', table_name='path')
    op.drop_index('path_skybox_image', table_name='path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('path_skybox_image', 'path', ['path_skybox_image'], unique=True)
    op.create_index('path_env_image', 'path', ['path_env_image'], unique=True)
    op.create_table('user',
    sa.Column('email', mysql.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
