# Build Stage
FROM node:20 as build-stage
WORKDIR /app
ARG VUE_APP_CLIENT_ID
ENV VUE_APP_CLIENT_ID=${VUE_APP_CLIENT_ID}
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

# Production Stage
FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
